# Copyright (c) 2000 - 2019 The Regents of the University of California.
# All rights reserved.	
# This includes the Generic yaml2rpm Makefile - most packaging should
# be able to use this.

include $(YAML2RPM_HOME)/sys/Makefile
clean:
	- /bin/rm -r  ../logrotate.d ../rsyslog.d ../BUILD/xCAT* ../BUILD/etc ../BUILD/*scripts ../BUILD/perl-xCAT* 
	- /bin/rm -f ../BUILD/core-rpms* ../BUILD/LICENSE.html
